"""create profile table

Revision ID: bcd9bff6b435
Revises: c5e038c42aca
Create Date: 2024-08-03 13:04:09.099170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bcd9bff6b435"
down_revision: Union[str, None] = "c5e038c42aca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("first_name", sa.VARCHAR(length=50), nullable=False))
    op.add_column("users", sa.Column("last_name", sa.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
